apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: denodo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eloieloie/argocd_eloi_mac.git
    targetRevision: main
    path: .
    directory:
      include: 'denodo-dev.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
